# Circleci build file
# https://circleci.com/gh/ConsenSys/karl
version: 2
jobs:
  build:
    working_directory: ~/karl
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-			

      - run:
        command: |
          sudo pip install pipenv
          pipenv install

      - run:
          name: Black style check
          command: |
            pip3 install --user black
            python3 -m black --check ~/karl/

      - run:
          name: Ensuring that setup script is functional
          command: python3 setup.py install
          working_directory: ~/karl

      - store_test_results:
        path: test-results
      - store_artifacts:
        path: test-results
        destination: tr1